"""Pydantic schema exports for external usage."""

from .lead import LeadCreate, LeadRead, LeadListResponse, LeadUpdate, LeadStatusUpdate
from .activity import ActivityCreate, ActivityRead
from .score import (
    ScoreBreakdown,
    ScoreResponse,
    AIScoreResponse,
    InsightResponse,
    PrioritizedLeadItem,
    PrioritizedLeadsResponse,
    ScoringAnalyticsResponse,
)
from .user import UserCreate, UserLogin, UserResponse, Token, TokenData
from .assignment import AssignmentCreate, AssignmentResponse, AssignmentWithDetails
from .assignment_rule import (
    AssignmentRuleCreate,
    AssignmentRuleRead,
    AssignmentRuleUpdate,
    AssignmentRuleConditions,
    AssignmentRuleToggleRequest,
    AssignmentRuleTestResponse,
    AssignmentEligibleRep,
    AssignmentRuleApplyRequest,
    AssignmentRuleApplyResponse,
)
from .note import NoteCreate, NoteResponse, NotificationResponse
from .ai import (
    AIInsightResponse,
    EmailTemplateRequest,
    EmailTemplateResponse,
    NextBestActionResponse,
    ActionItem,
    ConversionProbability,
    TalkingPoint,
)
from .integrations import (
    EmailAccountRead,
    EmailMessageRead,
    SendEmailRequest,
    OAuthConnectResponse,
    OAuthCallbackResponse,
)
from .crm import (
    CRMIntegrationRead,
    PipedriveConnectRequest,
    CRMSyncTriggerRequest,
    SyncLogRead,
    SyncStatusResponse,
    ConflictResolutionRequest,
)
from .api_key import (
    APIKeyCreate,
    APIKeyUpdate,
    APIKeyRead,
    APIKeyListResponse,
    APIKeySecretResponse,
    APIKeyUsageResponse,
    APIKeyUsageSample,
)
from .webhook import (
    WebhookCreate,
    WebhookUpdate,
    WebhookRead,
    WebhookListResponse,
    WebhookTestRequest,
    WebhookDeliveryRead,
    WebhookDeliveryListResponse,
    WebhookSecretResponse,
)
from .public_api import (
    PublicLeadCreate,
    PublicLeadUpdate,
    PublicLeadResponse,
    PublicLeadListResponse,
    PublicActivityCreate,
    PublicUserInfo,
)

__all__ = [
    "LeadCreate",
    "LeadRead",
    "LeadUpdate",
    "LeadStatusUpdate",
    "LeadListResponse",
    "ActivityCreate",
    "ActivityRead",
    "ScoreBreakdown",
    "ScoreResponse",
    "AIScoreResponse",
    "InsightResponse",
    "PrioritizedLeadItem",
    "PrioritizedLeadsResponse",
    "ScoringAnalyticsResponse",
    "UserCreate",
    "UserLogin",
    "UserResponse",
    "Token",
    "TokenData",
    "AssignmentCreate",
    "AssignmentResponse",
    "AssignmentWithDetails",
    "NoteCreate",
    "NoteResponse",
    "NotificationResponse",
    "AssignmentRuleCreate",
    "AssignmentRuleRead",
    "AssignmentRuleUpdate",
    "AssignmentRuleConditions",
    "AssignmentRuleToggleRequest",
    "AssignmentRuleTestResponse",
    "AssignmentEligibleRep",
    "AssignmentRuleApplyRequest",
    "AssignmentRuleApplyResponse",
    "AIInsightResponse",
    "EmailTemplateRequest",
    "EmailTemplateResponse",
    "NextBestActionResponse",
    "ActionItem",
    "ConversionProbability",
    "TalkingPoint",
    "EmailAccountRead",
    "EmailMessageRead",
    "SendEmailRequest",
    "OAuthConnectResponse",
    "OAuthCallbackResponse",
    "CRMIntegrationRead",
    "PipedriveConnectRequest",
    "CRMSyncTriggerRequest",
    "SyncLogRead",
    "SyncStatusResponse",
    "ConflictResolutionRequest",
    "APIKeyCreate",
    "APIKeyUpdate",
    "APIKeyRead",
    "APIKeyListResponse",
    "APIKeySecretResponse",
    "APIKeyUsageResponse",
    "APIKeyUsageSample",
    "WebhookCreate",
    "WebhookUpdate",
    "WebhookRead",
    "WebhookListResponse",
    "WebhookTestRequest",
    "WebhookDeliveryRead",
    "WebhookDeliveryListResponse",
    "WebhookSecretResponse",
    "PublicLeadCreate",
    "PublicLeadUpdate",
    "PublicLeadResponse",
    "PublicLeadListResponse",
    "PublicActivityCreate",
    "PublicUserInfo",
]
